In [5]:
import sys
sys.path.append(r"D:\projects\TORCH\scratch_transformer")



import torch.nn.functional as F

In [6]:
import torch 
import torch.nn as nn
import pandas as pd
import re


# Data

In [7]:
with open(r"D:\projects\TORCH\shakespear LM\data\alllines.txt","r") as f :
    data = f.readlines()
data
text = " ".join(data)


## Cleaning

In [8]:
text = re.sub('"','',text)
# text = re.sub('\n','',text)
text = text.split("\n")


In [9]:
from transformers import BertTokenizer
tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")

In [10]:
T = tokenizer(text,return_tensors = 'pt',padding = True)

In [11]:
a = T["input_ids"][0]

In [12]:
T["attention_mask"][0]

tensor([1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
X, y = [],[]
for i in T["input_ids"]:
    X.append(i[:-1])
    y.append(i[1:])
    

In [14]:
X = torch.stack(X)
y = torch.stack(y)


In [15]:
from torch.utils.data import Dataset, DataLoader

class MyDataset(Dataset):
    def __init__(self, X, y):
        self.X = X
        self.y = y
    

    def __len__(self):
        return len(self.X)

    def __getitem__(self, idx):
        x = self.X[idx].to("cuda")
        y = self.y[idx].to("cuda")
        return x,y
dataset = MyDataset(X,y)
batch_size = 128
dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=True)

In [16]:
dataloader

In [17]:
import os
os.environ['CUDA_LAUNCH_BLOCKING'] = "1"


In [18]:
import torch, gc
gc.collect()
torch.cuda.empty_cache()

In [19]:
a = nn.Linear(20,1000)
a.weight

Parameter containing:
tensor([[-0.1300,  0.1455, -0.1072,  ..., -0.1731, -0.0302,  0.2057],
        [ 0.1906,  0.0544, -0.2065,  ..., -0.1836,  0.0604, -0.1718],
        [ 0.2162,  0.0160, -0.2074,  ..., -0.2172,  0.1974,  0.0429],
        ...,
        [ 0.2213, -0.0240,  0.0334,  ..., -0.1444, -0.1850,  0.1365],
        [-0.2047,  0.1883,  0.1660,  ..., -0.1735,  0.1012, -0.2201],
        [ 0.0522,  0.0119,  0.0462,  ...,  0.0126,  0.1537,  0.1849]],
       requires_grad=True)

In [47]:
c = b.weight

In [50]:
a.weight

Parameter containing:
tensor([[ 2.1365, -0.7716,  0.6072,  ...,  0.0522, -0.4370, -0.8701],
        [-0.0530,  1.3254, -1.0735,  ..., -0.6417, -1.8475, -0.1733],
        [ 0.6687, -0.2786, -0.6807,  ..., -0.8364, -0.2980,  0.2250],
        ...,
        [-0.2091, -0.0780,  0.2800,  ..., -0.7574, -0.1878, -0.0657],
        [ 0.4279, -0.0972,  0.1362,  ...,  0.9234, -0.4281,  1.4271],
        [-0.8144,  2.2673,  0.9204,  ...,  0.4303, -1.0732, -0.0223]],
       requires_grad=True)

In [49]:
a.weight = c

In [22]:
# import scratch_transformer
import helpers
from  helpers import get_param_num
import importlib
import attention_block
# importlib.reload(scratch_transformer)
import transformer
import torch.optim as optim
import Gpt
vocab_size = 10_000

model =Gpt.GPT(vocab_size).to("cuda")
get_param_num(model)

Total number of parameters: 31724968


31724968

In [23]:



# Define loss function and optimizer
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

# Load your dataset using DataLoader



# Training loop
num_epochs = 2

for epoch in range(num_epochs):
    model.train()  # Set the model to training mode
    total_loss = 0.0

    batch = 0
    for x,y in dataloader:
        
        
        optimizer.zero_grad()  # Zero the gradients
        outputs = model(x)  # Forward pass
        loss = criterion(y.float(),torch.argmax(outputs,dim=-1).float())  # Calculate the loss
        loss.requires_grad =True
        loss.backward()  # Backpropagation
        optimizer.step()  # Update weights
        total_loss += loss.item()
        batch +=1
        
        print("batch :",batch," Done!")
    
    average_loss = total_loss / len(dataloader)
    print(f"Epoch [{epoch+1}/{num_epochs}] - Loss: {average_loss:.4f}")

print("Training finished")


RuntimeError: CUDA error: device-side assert triggered

In [205]:
torch.save(model,"trained2Epochs.pt")

In [18]:
y[0]

tensor([6658, 1010, 4894, 1012,  102,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,   

In [19]:
torch.argmax(outputs,dim=-1).float()

tensor([[12796., 10071., 13508.,  ..., 12147., 12147., 15425.],
        [12796., 29938., 13124.,  ..., 26427., 15425., 15425.],
        [12796., 14983., 25381.,  ..., 14781., 15425., 15425.],
        ...,
        [12796., 19275.,  9340.,  ..., 15425., 15425., 15425.],
        [15852.,  7887., 25381.,  ..., 15425., 15425., 15425.],
        [12796., 25381., 24663.,  ..., 15425., 15425., 15425.]],
       device='cuda:0')

In [206]:
b  = tokenizer("We are impressed",return_tensors="pt")["input_ids"].to("cuda")

RuntimeError: The size of tensor a (5) must match the size of tensor b (4) at non-singleton dimension 0

In [102]:
b  = b[0][:-1]
b = b[None,:]

In [108]:
b

tensor([[ 101, 2057, 2024, 7622]], device='cuda:0')

In [119]:
b

tensor([[ 101, 2057, 2024, 7622,  102]], device='cuda:0')

In [107]:
model(b).shape


torch.Size([1, 4, 30000])

In [159]:
z = torch.argmax(model(b),dim=-1)

12103

In [154]:
a = z.tolist()

In [156]:
a[0].append(34243)

In [158]:
torch.Tensor(a)

tensor([[22611.,  1865., 25674., 11428., 12103., 34243.]])

In [153]:
a = z[0][-1]

In [152]:
a=a]

tensor([[22611,  1865, 25674, 11428, 12103]], device='cuda:0')

In [144]:
torch.cat((z,),dim=-1)

RuntimeError: zero-dimensional tensor (at position 1) cannot be concatenated

SyntaxError: cannot assign to function call (3271674273.py, line 1)

In [115]:
tokenizer.convert_ids_to_tokens(4970)

'chapel'

In [207]:
def generate_output(query,model,length = 40):
    result = []
    print(34234)
    inp  = tokenizer(query,return_tensors="pt")["input_ids"].to("cuda")
    inp  = inp[0][:-1]
    inp  = inp[None,:]
    for _ in range(length):        
        out  = model(inp)
        out  = torch.argmax(out,dim=-1)
        pred = int(out[0][-1])
        result.append(pred)
        out = out.tolist()
        out[0].append(pred)
        inp = torch.tensor(out).to("cuda")        

    return result




In [194]:
a

[24601,
 24601,
 24601,
 24601,
 24601,
 24601,
 24601,
 24601,
 24601,
 24601,
 24601,
 24601,
 24601,
 24601,
 24601,
 24601,
 24601,
 24601,
 24601,
 24601,
 24601,
 24601,
 24601,
 24601,
 24601,
 24601,
 24601,
 24601,
 24601,
 24601,
 24601,
 24601,
 24601,
 24601,
 24601,
 24601,
 24601,
 24601,
 24601,
 24601]

In [210]:
a = generate_output("hello i like to play games",model)

34234


In [211]:
tokenizer.decode(a)

'recited [unused306] fairsmates son nationale difficulties [unused525] methodist gustional essendon travelling attention bosch regina jonah delayednadst tormented loved roberta heading mascot transitioned laundry [unused893]naut haryanautter stratacodes mustang snap nun samurai ffdana flirting'

In [8]:
(512*2048+2048) + (512*2048+512)

2099712

In [47]:
ff = 512*2048+2048 + 512+2048+512

In [51]:
dec = 2* matt + ff

In [55]:
512 * 20000

10240000

In [54]:
dec*6  + 6*enc

19145088

In [59]:
262144 + 786432

1048576

In [40]:
matt

361152

In [58]:
512*512

262144

In [72]:
512 * 10000

5120000

In [75]:
(512 * 50000)

25600000

In [57]:
98304 * 8

786432

In [69]:
(512 * 2048 + 2048) + (512 * 2048 + 512) 

2099712

In [80]:
512 * 50000

25600000

In [77]:
25600000 + 37797888


63397888

In [71]:
3149824 * 12

37797888

In [70]:
2099712+1050112

3149824

In [ ]:
1050112

In [ ]:
1050624

In [68]:
787968 + 262144 +512

1050624

In [66]:
98496 * 8

787968

In [65]:
(512*64)*3 + 3*64

98496

In [64]:
3_145_728 * 12

37748736

In [62]:
2_097_152 + 1_048_576

3145728

In [61]:
512*2048*2

2097152

In [56]:
(512*64)*3

98304

In [49]:

enc = matt+ff

In [53]:
6*enc

8489088

In [45]:
matt = 3*(64*512+64)+512*512 + 512

In [46]:
matt

361152

In [27]:
2* (6*(((3*(64*512)*8)+512*512) + ff))

25196544

In [16]:
matt

360448

In [15]:
2*((ff+matt)*6)

29521920

In [ ]:



import torch.optim as optim
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

# Training loop
num_epochs = 10
for epoch in range(num_epochs):
    model.train()  # Set the model to training mode
    running_loss = 0.0
    
    for batch_inputs, batch_targets in dataloader:  # Iterate over batches
        optimizer.zero_grad()  # Clear gradients
        
        
        
        # Forward pass
        outputs = model(batch_inputs,batch_targets)
        o = torch.argmax(outputs,dim=-1)
        
        # Compute loss
        loss = criterion(outputs, batch_targets)
        
        # Backpropagation
        loss.backward()
        
        # Update weights
        optimizer.step()
        
        running_loss += loss.item()
    
    average_loss = running_loss / len(dataloader)
    print(f"Epoch [{epoch+1}/{num_epochs}] - Loss: {average_loss:.4f}")







RuntimeError: shape '[8, 32, 1]' is invalid for input of size 147456

In [ ]:
X.shape

torch.Size([168380, 7, 8])

In [ ]:
outputs.shape

torch.Size([32, 8, 12766])

In [ ]:
batch_targets.shape

torch.Size([32, 2])

In [ ]:
X.shape
y.shape

torch.Size([1178667])

In [ ]:
torch.argmax(outputs,dim=-1)

tensor([[12413, 10772,  8587,  6992, 11791, 11791, 11791, 11791],
        [  226,  1622,  6993,   763,   763,   763,   763,   763],
        [ 8984, 11280,  9499, 11280,  4671,  4671,  4671,  4671],
        [10774, 10589,  3882,  3882,  3882,  3882,  3882,  3882],
        [ 7796, 10182,  1586, 11171,  5189, 10157,  1553,  4019],
        [ 3313,  4483,  2997,  2997,  2997,  2997,  2997,  2997],
        [ 3580,  2259,  2259,  2259,  2259,  2259,  2259,  2259],
        [ 4931,  9304,  9948, 12230, 12230, 12413,  7303,  8766],
        [ 2339, 11213,  7011,  4966,  4483, 12230,   729,   729],
        [ 3415,  7892,  1943, 11708,  6077,   729,   729,   729],
        [11280, 12230,   313,   313,   313,   313,   313,   313],
        [ 9174,  4483,  6897,  6897, 10957,  4575,  4575,  4575],
        [ 1453, 11280, 12230,   313,   313,   313,   313,   313],
        [12230, 12230, 11120, 12099, 12099, 12099, 12099, 12099],
        [12230, 12230,   968,  1971, 12099, 12099, 12099, 12099],
        [1

In [ ]:
torch.argmax(torch.argmax(outputs,dim=-1),dim=-1)

tensor([0, 2, 1, 0, 3, 1, 0, 5, 5, 3, 1, 4, 2, 0, 0, 4, 5, 1, 1, 2, 4, 1, 0, 6,
        1, 3, 1, 5, 2, 1, 1, 3])

In [ ]:
o.shape

torch.Size([32, 7, 8])

In [ ]:
outputs.shape

torch.Size([32, 7, 8, 12766])

In [ ]:
batch_targets.shape

torch.Size([32, 7])

In [ ]:
embedding_layer = nn.Embedding(4, 10)


In [ ]:
a = torch.Tensor([[0]]).type(torch.int)

embedding_layer(a)

tensor([[[-0.0618,  0.3907,  0.1098, -1.4951, -0.2013,  1.2801, -0.2054,
           0.1741,  0.5938, -0.2920]]], grad_fn=<EmbeddingBackward0>)

In [ ]:
embedding.weight.data[:2] = new_embedding_values  # Set the bv
first two embeddings to the new values


In [ ]:
embedding_layer.weight.data[0]

tensor([-0.0343, -0.6778, -0.2039, -0.3394,  0.8289,  1.0515,  1.2246, -0.0811,
        -0.2167, -0.2287])

IndexError: index out of range in self

In [ ]:
padded_data = pad_sequence(a, batch_first=True, padding_value=12)


IndexError: dimension specified as 0 but tensor has no dimensions

In [ ]:
print(batch_inputs)

tensor([[[11146.,   -inf,   -inf,  ...,   -inf,   -inf,   -inf],
         [11146.,    23.,   -inf,  ...,   -inf,   -inf,   -inf],
         [11146.,    23., 12340.,  ...,   -inf,   -inf,   -inf],
         ...,
         [11146.,    23., 12340.,  ...,   -inf,   -inf,   -inf],
         [11146.,    23., 12340.,  ...,  3476.,   -inf,   -inf],
         [11146.,    23., 12340.,  ...,  3476., 10291.,   -inf]],

        [[ 3314.,   -inf,   -inf,  ...,   -inf,   -inf,   -inf],
         [ 3314.,  7296.,   -inf,  ...,   -inf,   -inf,   -inf],
         [ 3314.,  7296., 10671.,  ...,   -inf,   -inf,   -inf],
         ...,
         [ 3314.,  7296., 10671.,  ...,   -inf,   -inf,   -inf],
         [ 3314.,  7296., 10671.,  ...,  9606.,   -inf,   -inf],
         [ 3314.,  7296., 10671.,  ...,  9606., 11146.,   -inf]],

        [[11029.,   -inf,   -inf,  ...,   -inf,   -inf,   -inf],
         [11029.,  4214.,   -inf,  ...,   -inf,   -inf,   -inf],
         [11029.,  4214.,   226.,  ...,   -inf,   -inf,   

tensor(2445, dtype=torch.int32)

tensor([3476, 2445,    0,    0,    0,    0,    0,    0], dtype=torch.int32)