In [1]:
from helpers import get_param_num
import torch 
import torch.nn as nn

In [ ]:
from attention_block import Attention_Block
Attention_Block()

In [42]:
a = torch.rand(123)

In [50]:
b= nn.Linear(123,123,bias = False
             )
b.weight.data = torch.eye(123)

print(a)
b(a) 


tensor([0.0430, 0.9147, 0.1368, 0.5885, 0.4144, 0.7169, 0.0027, 0.0746, 0.4161,
        0.3880, 0.3759, 0.0615, 0.0412, 0.3498, 0.6788, 0.6110, 0.5153, 0.5850,
        0.6866, 0.8740, 0.5532, 0.4790, 0.9969, 0.0618, 0.9934, 0.9529, 0.1372,
        0.6175, 0.7070, 0.6185, 0.8559, 0.2855, 0.6112, 0.2164, 0.9712, 0.7035,
        0.9965, 0.7054, 0.0127, 0.6756, 0.6323, 0.0121, 0.8615, 0.3093, 0.0826,
        0.1075, 0.2682, 0.4951, 0.8457, 0.9204, 0.0221, 0.6619, 0.0107, 0.0739,
        0.2116, 0.4047, 0.7988, 0.1389, 0.5971, 0.8722, 0.5600, 0.4953, 0.4316,
        0.4316, 0.2752, 0.6699, 0.3131, 0.4004, 0.7912, 0.0869, 0.4410, 0.4506,
        0.0575, 0.1379, 0.2720, 0.0864, 0.3694, 0.4746, 0.8273, 0.6181, 0.7925,
        0.8974, 0.3565, 0.7967, 0.2007, 0.6868, 0.7469, 0.2755, 0.1016, 0.7986,
        0.9311, 0.0448, 0.8961, 0.5783, 0.0910, 0.2596, 0.4325, 0.7601, 0.6582,
        0.6196, 0.6497, 0.0870, 0.5796, 0.0573, 0.8086, 0.0533, 0.9792, 0.5432,
        0.1177, 0.4214, 0.1680, 0.0209, 

tensor([0.0430, 0.9147, 0.1368, 0.5885, 0.4144, 0.7169, 0.0027, 0.0746, 0.4161,
        0.3880, 0.3759, 0.0615, 0.0412, 0.3498, 0.6788, 0.6110, 0.5153, 0.5850,
        0.6866, 0.8740, 0.5532, 0.4790, 0.9969, 0.0618, 0.9934, 0.9529, 0.1372,
        0.6175, 0.7070, 0.6185, 0.8559, 0.2855, 0.6112, 0.2164, 0.9712, 0.7035,
        0.9965, 0.7054, 0.0127, 0.6756, 0.6323, 0.0121, 0.8615, 0.3093, 0.0826,
        0.1075, 0.2682, 0.4951, 0.8457, 0.9204, 0.0221, 0.6619, 0.0107, 0.0739,
        0.2116, 0.4047, 0.7988, 0.1389, 0.5971, 0.8722, 0.5600, 0.4953, 0.4316,
        0.4316, 0.2752, 0.6699, 0.3131, 0.4004, 0.7912, 0.0869, 0.4410, 0.4506,
        0.0575, 0.1379, 0.2720, 0.0864, 0.3694, 0.4746, 0.8273, 0.6181, 0.7925,
        0.8974, 0.3565, 0.7967, 0.2007, 0.6868, 0.7469, 0.2755, 0.1016, 0.7986,
        0.9311, 0.0448, 0.8961, 0.5783, 0.0910, 0.2596, 0.4325, 0.7601, 0.6582,
        0.6196, 0.6497, 0.0870, 0.5796, 0.0573, 0.8086, 0.0533, 0.9792, 0.5432,
        0.1177, 0.4214, 0.1680, 0.0209, 

In [29]:
b.weight.data

tensor([[1., 0., 0.,  ..., 0., 0., 0.],
        [0., 1., 0.,  ..., 0., 0., 0.],
        [0., 0., 1.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 1., 0., 0.],
        [0., 0., 0.,  ..., 0., 1., 0.],
        [0., 0., 0.,  ..., 0., 0., 1.]])

In [1]:
from feedForward import Feed_Forward


input_size = 128
output_size = 64
model = Feed_Forward(input_size, output_size)

# Count the number of parameters
total_params = sum(p.numel() for p in model.parameters())
print(f"Total number of parameters: {total_params}")

Total number of parameters: 49472


In [3]:
(1,128) X (128,256) => (1,256) X (1,64)

SyntaxError: invalid syntax (2607347938.py, line 1)

In [3]:
4*64

256

In [4]:
test = torch.rand((1,128))
model(test)

tensor([[0.0000, 0.0000, 0.0000, 0.0875, 0.0803, 0.1061, 0.0000, 0.0000, 0.0973,
         0.0000, 0.0476, 0.0000, 0.2296, 0.1238, 0.0000, 0.0000, 0.1309, 0.0000,
         0.0204, 0.1597, 0.0000, 0.1159, 0.0679, 0.0000, 0.2465, 0.0366, 0.0000,
         0.0000, 0.0277, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0954, 0.0000, 0.0178, 0.0000, 0.1735, 0.0997, 0.0142, 0.1003, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0336, 0.1102, 0.1245, 0.0000, 0.0000, 0.1014,
         0.0257, 0.0000, 0.0000, 0.1484, 0.0000, 0.0000, 0.0000, 0.0138, 0.0000,
         0.2103]], grad_fn=<ReluBackward0>)

In [5]:
from encoder import Encoder
enc = Encoder(6,16,10,32,32,32)

total_params = sum(p.numel() for p in enc.parameters())
print(f"Total number of parameters: {total_params}")
test = torch.rand((5,16))


Total number of parameters: 141952


In [12]:
att(test)

TypeError: cannot assign 'torch.FloatTensor' as child module 'Q' (torch.nn.Module or None expected)

In [10]:
for  att,ff in enc.blocks:
    print(att,ff)
    print(42342424)


Attention_Block(
  (Q): Linear(in_features=16, out_features=320, bias=False)
  (V): Linear(in_features=16, out_features=320, bias=False)
  (K): Linear(in_features=16, out_features=320, bias=False)
  (conc_heads): Linear(in_features=320, out_features=16, bias=True)
) Feed_Forward(
  (l1): Linear(in_features=32, out_features=64, bias=True)
  (l2): Linear(in_features=64, out_features=16, bias=True)
)
42342424
Attention_Block(
  (Q): Linear(in_features=16, out_features=320, bias=False)
  (V): Linear(in_features=16, out_features=320, bias=False)
  (K): Linear(in_features=16, out_features=320, bias=False)
  (conc_heads): Linear(in_features=320, out_features=16, bias=True)
) Feed_Forward(
  (l1): Linear(in_features=32, out_features=64, bias=True)
  (l2): Linear(in_features=64, out_features=16, bias=True)
)
42342424
Attention_Block(
  (Q): Linear(in_features=16, out_features=320, bias=False)
  (V): Linear(in_features=16, out_features=320, bias=False)
  (K): Linear(in_features=16, out_features=

In [5]:
test

tensor([[0.3674, 0.7387, 0.1723, 0.2291, 0.0548, 0.4521, 0.2220, 0.8759, 0.9160,
         0.0775, 0.8661, 0.8004, 0.0339, 0.4578, 0.2771, 0.9520],
        [0.7591, 0.7433, 0.3570, 0.3890, 0.8373, 0.8834, 0.9863, 0.5260, 0.7355,
         0.7413, 0.4700, 0.0075, 0.4724, 0.4950, 0.2829, 0.6522],
        [0.3442, 0.9564, 0.9601, 0.3779, 0.2610, 0.5725, 0.0811, 0.6971, 0.7743,
         0.7053, 0.4369, 0.1443, 0.1607, 0.3055, 0.4420, 0.7519],
        [0.4820, 0.7941, 0.3467, 0.1407, 0.0290, 0.2657, 0.2115, 0.8567, 0.1753,
         0.4351, 0.9540, 0.6656, 0.5675, 0.8200, 0.8916, 0.9789],
        [0.8254, 0.4508, 0.3901, 0.9171, 0.5026, 0.3376, 0.9864, 0.1767, 0.6384,
         0.4813, 0.1636, 0.5627, 0.7647, 0.2236, 0.2098, 0.9506]])

In [13]:
enc.parameters

<bound method Module.parameters of Encoder(
  (norm): LayerNorm((32,), eps=1e-05, elementwise_affine=True)
)>

In [12]:
enc.parameters

<bound method Module.parameters of Encoder(
  (norm): LayerNorm((32,), eps=1e-05, elementwise_affine=True)
)>